### ISSUE TITLE
Hello @blotfi is there a reason why you have not used all the TFT width ? or its because initial code was for a portrait TFT mode

### ISSUE THREAD

**Issue by blotfi** [blotfi/ESP32-Radio-with-Spectrum-analyzer#2]
Hello @blotfi is there a reason why you have not used all the TFT width ? or its because initial code was for a portrait TFT mode

Thanks

_Originally posted by @gcharles81 in https://github.com/Edzelf/ESP32-Radio/issues/86#issuecomment-635799288_

**Comment by blotfi** [comment]
Yes indeed, I tried to go for the 320 pix but no way.<br/> When I go beyond the 240, the bars are displayed badly on the left again (overprinted)
even I have specified
```
#define dsp_getwidth()          320                                // Adjust to your display
#define dsp_getheight()         240                                // Get height of screen
```
in `ILI9341.h`

I think that this a problem of the fast drawing method of the bars in the `Adafruit_GFX` lib
If you have time, perhaps you can dig into `void displaySpectrum()`
replace
```uint8_t larg = dsp_getheight() / bands-2; //todo why we can't go up to 320```
with
```uint8_t larg = dsp_getwidth() / bands-2; ```
and you will see
best regards
Lotfi

**Comment by gcharles81** [comment]
Hello blotfi , thanks ,  issue fixed now 

I have looked into the code and at the beginning i simplified a bit the naming so its more understandable ,your issue was coming from posi as it was defined as uint8_t so at a value of 255 it was resetting back to zero. so i defined it as uint16_t .

My code is the below and works fine now 
![Spectrum](https://user-images.githubusercontent.com/7485648/83298352-8f826100-a1f4-11ea-8fb7-e0013b6ed572.png)


//
//**************************************************************************************************
// DISPLAY SPECTRUM *
//**************************************************************************************************
// *
//**************************************************************************************************
void displaySpectrum() {
  
  uint8_t Bar_width = 21; // The width of the bar 
  uint8_t Pitch_X = 23; // The pitch index between bars  
  uint8_t StartX_location = 0;// star t 
  uint16_t posi = 0;
    
    boolean visual = true;
//    if (enc_menu_mode == MENU)
//    {
//        visual = false;
//    }
    if (bands != prevbands) {
        prevbands = bands;
    if (visual)
        dsp_fillRect (0, Spectrum_y0, dsp_getwidth(), Spectrum_hy + 1, BLACK);
    }
  
  posi = StartX_location; // Set the start X location for 1st bar 
    
  for (uint8_t i = 0; i < bands; i++) // Handle all sections
    {       
  
  
        if (visual) {
            if (spectrum[i][0] > spectrum[i][1]) {
                dsp_fillRect (posi, Spectrum_y0 + Spectrum_hy - spectrum[i][0], Bar_width, spectrum[i][0], GREEN);
                dsp_fillRect (posi, Spectrum_y0, Bar_width, Spectrum_hy - spectrum[i][0], BLACK);
            } else
                dsp_fillRect (posi, Spectrum_y0, Bar_width, Spectrum_hy - spectrum[i][0], BLACK);
        }
        if (spectrum[i][2] > 0) spectrum[i][2]--;
        if (spectrum[i][0] > spectrum[i][2]) spectrum[i][2] = spectrum[i][0];
        if (visual)
            dsp_fillRect (posi, Spectrum_y0 + Spectrum_hy - spectrum[i][2] - 3, Bar_width, 2, RED);
        spectrum[i][1] = spectrum[i][0];
    
    posi = posi + Pitch_X;// We index one pitch in X 
  }
}

//**************************************************************************************************
//**************************************************************************************************
//

**Comment by blotfi** [comment]
GG for the uint16_t 
I don't know why I didn't see that ;-)
Will update the code, thanks

**Comment by blotfi** [comment]
```
//**************************************************************************************************
// DISPLAY SPECTRUM *
//**************************************************************************************************
// *
//**************************************************************************************************
void displaySpectrum() {
    uint8_t larg = dsp_getwidth() / bands-2;
    uint16_t  posi = 5; // start location of the first bar
    boolean visual = true;
//    if (enc_menu_mode == MENU)
//    {
//        visual = false;
//    }
    if (bands != prevbands) {
        prevbands = bands;
    if (visual)
        dsp_fillRect (0, Spectrum_y0, dsp_getwidth(), Spectrum_hy + 1, BLACK);
    }
    for (uint8_t i = 0; i < bands; i++) // Handle all sections
    {
        if (visual) {
            if (spectrum[i][0] > spectrum[i][1]) {
                dsp_fillRect (posi, Spectrum_y0 + Spectrum_hy - spectrum[i][0], larg, spectrum[i][0], GREEN);
                dsp_fillRect (posi, Spectrum_y0, larg, Spectrum_hy - spectrum[i][0], BLACK);
            } else
                dsp_fillRect (posi, Spectrum_y0, larg, Spectrum_hy - spectrum[i][0], BLACK);
        }
        if (spectrum[i][2] > 0) spectrum[i][2]--;
        if (spectrum[i][0] > spectrum[i][2]) spectrum[i][2] = spectrum[i][0];
        if (visual)
            dsp_fillRect (posi, Spectrum_y0 + Spectrum_hy - spectrum[i][2] - 3, larg, 2, RED);
        spectrum[i][1] = spectrum[i][0];
        posi += larg + 2;
    }
}

```
