### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Aleks-Ale** [blotfi/ESP32-Radio-with-Spectrum-analyzer#4]
1. Could you please check this stream:
preset_03 = airspectrum.cdnstream1.com:8000/1261_192 #  3 - Magic Oldies Florida
I can hear stuttering. Can you understand the cause of this problem? Bit rate is very low?
2. Some problems in the first row.
mp3 mode: 
![2020-08-20_20-43-22](https://user-images.githubusercontent.com/69778440/90806934-67ebf200-e326-11ea-8504-2f69ed70d81a.png)
also no name of track
3. After switching to radio:
![2020-08-20_20-45-59](https://user-images.githubusercontent.com/69778440/90807288-ed6fa200-e326-11ea-9fa1-0b746b7db890.png)
Thank you!

**Comment by blotfi** [comment]
put the streams that you want
I suggest using RadioSure (for Windows) to get the web addy

for the first line, yes, there is an overwrite / clearing text issue
that is pending from the original code
depending on the screen used, one has to adapt the code / dimension of clearing
When I will have time, I will get into the code again
but not these days...

Also I forked this code to another one: https://github.com/blotfi/ESP32-Radio-with-SalatTime
which I will develop in the future, since it includes the spectrum + other features that I use (but does not interest many others I suppose)

**Comment by Aleks-Ale** [comment]
Thank you for your answer!
Yes, everyone has their own preferences and wishes. 
For example, I would like to combine web radio with a large clock with date and day of the week. 
Display in portrait mode. 1/3 for clock and 2/3 for web radio. 
It can be beautiful to display the station logo on the screen, for example, from the SD card. 
For the touch screen it is possible to make a separate page with logos and names of stations for selection. 
If any of these ideas seem interesting to you, then I would be grateful for the implementation. 
This requires a lot of experience and a lot of knowledge. 
Unfortunately, I am only at the beginning of the road of knowledge.
PS: Another problem just appeared. The web radio independently switched from listening to the radio to the mp3 playback mode and started playing mp3 from the SD card.

Best wishes,
Alex

**Comment by blotfi** [comment]
> PS: Another problem just appeared. The web radio independently switched from listening to the radio to the mp3 playback mode and started playing mp3 from the SD card.

this seems like an internet connexion failure, it switch to the next (as when a song finish)
of it has received an IR code for another remote control

For the big clock and titles, I agree, I hope to do it when I will have time
